GET https://backend-nopal-505940949397.us-central1.run.app/api/users 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6ImJlYmFzIiwiZW1haWwiOiJiZWJhc0BnbWFpbCIsImdlbmRlciI6ImJlYmFzIiwiY3JlYXRlZEF0IjoiMjAyNS0wNS0wOFQwMzoxODoxOC4wMDBaIiwidXBkYXRlZEF0IjoiMjAyNS0wNS0yMFQwMTo1NDoxOS4wMDBaIiwiaWF0IjoxNzQ3NzA2MDgxLCJleHAiOjE3NDc3MDYzODF9.PlaaNJwiSRMHR3owHG2sFzosvW0oFw9a2hBEYf9vDVo

POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "name":"bebas",
    "email":"bebas@gmail",
    "gender":"bebas",
    "password":"bebas"
}

###

POST https://backend-nopal-505940949397.us-central1.run.app/api/users/login
Content-Type: application/json

{
    "email":"bebas@gmail",
    "password":"bebas"
}

###

PUT http://localhost:5000/api/users/edit-user/3
Content-Type: application/json

{
    "name": "bebas updated",
    "email": "bebas_updated@gmail.com",
    "gender": "bebas updated",
    "password": "bebas123"
}

###

DELETE http://localhost:5000/api/users/2

###

# endpoint kebawah ini tidak digunakan, alias salah, 404 indikasi endpoin salah

POST http://localhost:5000/add-user 
Content-Type: application/json

{
    "name": "tes",
    "email": "tes@tes.com",
    "gender": "Male"
}

### 

PUT http://localhost:5000/edit-user/1
Content-Type: application/json

{
    "name": "tessss",
    "email": "tesss@tessss.com",
    "gender": "Male"
}

###

DELETE http://localhost:5000/delete-user/17